runtime: nodejs
env: flex
threadsafe: true
automatic_scaling:
  max_num_instances: 1
env_variables:
  MONGO_URL: 'mongodb://user1:admin123@ds155644.mlab.com:55644/facsyn010118'
  ROOT_URL: 'https://www.facsyn.com'
  METEOR_SETTINGS: '{}'